### ISSUE TITLE
Failure to do uniq control with registration with a special name in the username field.

### ISSUE THREAD

**Issue by hhuseyincihangir** [heroiclabs/nakama-godot#46] opened 2020-06-26 20:19 UTC
I am currently developing a multiplayer game using nakama on Godot. In the nakama database opened by Nakama in CockroachDB, the email address in the users table appears as uniq. However, when registered with the registered email address, the server returns a positive response without any error. In the Godot client, the e-mail address received from the user while registering is registered in both the user name field and the e-mail field. When trying to record this separately, the email address should be uniq and give an error, but a positive message is returned as the registration is done.

- Corrections I made to enter user's username instead of email in username field.
ServerConnection.gd 
![resim](https://user-images.githubusercontent.com/15706050/85897160-6dcfc600-b802-11ea-94e6-919249fefedb.png)
Authenticator.gd
![resim](https://user-images.githubusercontent.com/15706050/85897227-922ba280-b802-11ea-8ab0-4581eae3f7f6.png)

**Comment by Faless** [comment] 2020-06-29 11:03
I'm not sure I understand what the problem is. None of those 2 files you changed are part of the Nakama Godot API.
In my tests, when registering a **new** user via email without specifying a username you will get a randomly generated username (that you can then update via `update_account_async`)
Can you provide a minimal reproduction project that shows the issue?

**Comment by hhuseyincihangir** [comment] 2020-06-29 12:46
Would you try to get the username from the user while registering? When you do this (Defined as unique in the user database.) someone else can register with the same username. Also, it is not added in a new user. 
To test this, add a username field to the registration screen in [Demo Project](https://github.com/heroiclabs/nakama-godot-demo) and make changes to the images. You'll see.

**Comment by hhuseyincihangir** [comment] 2020-08-25 06:45
How can we solve this?

**Comment by dsnopek** [comment] 2022-03-02 21:50
Ah, the code references in the description are to the [demo project](https://github.com/heroiclabs/nakama-godot-demo).

However, it's also unclear to me what exactly the problem is as it relates to the Godot client. If the server is reporting an error, and the Godot client is reporting that as a success, that would definitely be a bug to fix here! If that's the case, please provide a minimal reproduction project. But if the server is reporting success and the Godot client is just passing that along, then that is a bug or support request for the [Nakama project](https://github.com/heroiclabs/nakama) itself.

I'm going to close this issue for now, but we can always re-open it if more information is provided! Thanks :-)

**Closed by dsnopek** 2022-03-02 21:50 UTC
