### ISSUE TITLE
Branching or naming scheme required to match sdk version with server version

### ISSUE THREAD

**Issue by jasonwinterpixel** [heroiclabs/nakama-godot#71] opened 2021-05-20 16:20 UTC
This sdk currently only works with nakama server 2.x

There is no indication of this limitation.

A major version of the SDK should be compatable with the same major version of the server.

eg) sdk version 2.x works with server version 2.x, sdk version 3.x works with server version 3.x

I suggest that master branch on this repo always be the latest version of the sdk, but there should be a branch named 2.x that contains the latest version of the sdk that works against nakama server 2.x

**Comment by mofirouz** [comment] 2021-05-20 16:22
There aren’t any backwards incompatible changes to the API between Nakama 2 and Nakama 3. 

Can you describe what you are seeing that doesn’t work in Nakama 3?

**Comment by jasonwinterpixel** [comment] 2021-05-25 21:18
Both of these pull requests fix things that dont work when using Nakama Server v3.x with the master branch of this SDK repo.

Looks like the payload on RPCs changed from being a query param to being in the body:
https://github.com/heroiclabs/nakama-godot/pull/69


And looks like the error response changed from using the 'error' key to the 'message' key:
https://github.com/heroiclabs/nakama-godot/pull/68

**Comment by Faless** [comment] 2021-07-09 13:16
As mentioned by @mofirouz there shouldn't be incompatible changes, those 2 issues where caused by bugs.
Closing since the addon is supposed to support both Nakama 2 and Nakama 3.

**Closed by Faless** 2021-07-09 13:16 UTC
