### ISSUE TITLE
Sending state from web client does not work immediately after joining match

### ISSUE THREAD

**Issue by reasv** [heroiclabs/nakama-godot#36] opened 2020-05-11 08:57 UTC
I am using Godot 3.2 and latest Nakama from Docker.
My clients all match and connect correctly, and use `socket.send_match_state_async()` to exchange messages, This works between Desktop clients.

However HTML clients do not seem to be sending messages. They will receive them from desktop clients but not send them successfully.
This issue only presents itself when sending a message **immediately** after `yield(socket.join_matched_async(p_matched), "completed")`

It **does** work correctly in my "real" netcode which only starts sending state after a while, and from a different function.

I suspect this might be due to me misunderstanding how to use async in GDScript, however I'm opening an issue just in case.

Here's a sample of code that reproduces the bug, mostly copied from the tutorials:
```
func _ready():
    socket.connect("received_matchmaker_matched", self, "_on_channel_matchmaker_matched")
    socket.connect("received_match_state", self, "_on_match_state")

func _on_channel_matchmaker_matched(p_matched : NakamaRTAPI.MatchmakerMatched):
    #print("Received MatchmakerMatched message: %s" % [p_matched])
    print("Matched opponents: %s" % [p_matched.users])
    var joined_match = yield(socket.join_matched_async(p_matched), "completed")
    if joined_match.is_exception():
        print("An error occured: %s" % joined_match)
        return
    print("Joined match: %s" % [joined_match.match_id])
    var op_code = 1
    var new_state = {"hello": "world"}
    var send_state = yield(socket.send_match_state_async(joined_match.match_id, op_code, JSON.print(new_state)), "completed")
    print("Sent: ", send_state)
    emit_signal("matchmaker_matched", joined_match)

func _on_match_state(p_state : NakamaRTAPI.MatchData):
    print("Received match state with opcode %s, data %s" % [p_state.op_code, parse_json(p_state.data)])
```
Of course you need to log in and matchmake before this, but that's all working fine.

**Comment by Faless** [comment] 2020-05-12 10:22
I did some tests, and I was able to reproduce in some cases (although not reliably).
Is is possible that the state is actually sent, but instead the other client has not yet completed its join?
To explain further, take this timed sequence:
1. Socket 1 receives matched event
2. Socket 2 receives matched event
3. Socket 1 ask to join
4. Socket 2 ask to join
5. Socket 1 join complete (it is now participating in the match)
6. Socket 1 send the state (but socket 2 is not yet participating)
7. Socket 2 join complete (it is now participating in the match)
8. Socket 2 send the state (socket 1 is participating, so it receives the sent state)

When events happen in this order, socket 2 will not receive the state from socket 1 since when it was sent, socket 2 join had yet to complete.

Can you confirm from your server log that the message is not actually sent? Or is it just not received from the other client? Can you provide a server log when this happen?

See my log for when I'm able to reproduce:

```
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.432Z","msg":"Sending *rtapi.Envelope_Match message","uid":"b48e37c2-120c-4b47-9690-c05adb6a1ca4","sid":"b578c46d-98c3-407e-828c-4be170875299","envelope":"cid:\"2\" match:<match_id:\"1f301c43-e474-423a-9fa7-953efad009c5.\" self:<user_id:\"b48e37c2-120c-4b47-9690-c05adb6a1ca4\" session_id:\"b578c46d-98c3-407e-828c-4be170875299\" username:\"QtWAlPPMeT\" > > "}
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.432Z","msg":"Processing presence event","joins":1,"leaves":0}
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.439Z","msg":"Received *rtapi.Envelope_MatchDataSend message","uid":"b48e37c2-120c-4b47-9690-c05adb6a1ca4","sid":"b578c46d-98c3-407e-828c-4be170875299","cid":"3","message":{"MatchDataSend":{"match_id":"1f301c43-e474-423a-9fa7-953efad009c5.","op_code":1,"data":"eyJhIjoxfQ=="}}}
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.442Z","msg":"Received *rtapi.Envelope_MatchJoin message","uid":"b48e37c2-120c-4b47-9690-c05adb6a1ca4","sid":"ec0057c7-0a2d-40e3-be4b-23a4d5a653db","cid":"2","message":{"MatchJoin":{"Id":{"Token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODkyNzg3MzksIm1pZCI6IjFmMzAxYzQzLWU0NzQtNDIzYS05ZmE3LTk1M2VmYWQwMDljNS4ifQ.-Ckhfc_Pr2Jjdi-rR6jQeqOXXqwcvsL3QKXelTXsE2I"}}}}
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.442Z","msg":"Processing presence event","joins":1,"leaves":0}
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.442Z","msg":"Sending *rtapi.Envelope_Match message","uid":"b48e37c2-120c-4b47-9690-c05adb6a1ca4","sid":"ec0057c7-0a2d-40e3-be4b-23a4d5a653db","envelope":"cid:\"2\" match:<match_id:\"1f301c43-e474-423a-9fa7-953efad009c5.\" size:1 presences:<user_id:\"b48e37c2-120c-4b47-9690-c05adb6a1ca4\" session_id:\"b578c46d-98c3-407e-828c-4be170875299\" username:\"QtWAlPPMeT\" > self:<user_id:\"b48e37c2-120c-4b47-9690-c05adb6a1ca4\" session_id:\"ec0057c7-0a2d-40e3-be4b-23a4d5a653db\" username:\"QtWAlPPMeT\" > > "}
nakama         | {"level":"debug","ts":"2020-05-12T10:18:29.445Z","msg":"Received *rtapi.Envelope_MatchDataSend message","uid":"b48e37c2-120c-4b47-9690-c05adb6a1ca4","sid":"ec0057c7-0a2d-40e3-be4b-23a4d5a653db","cid":"3","message":{"MatchDataSend":{"match_id":"1f301c43-e474-423a-9fa7-953efad009c5.","op_code":1,"data":"eyJhIjoxfQ=="}}}
```

As you can see the server receives `Envelope_MatchDataSend` from the first client **before** the `Envelope_MatchJoin` from the second client.

**Comment by reasv** [comment] 2020-05-12 12:01
>Is is possible that the state is actually sent, but instead the other client has not yet completed its join?

Yes, there does seem to be a race condition here, I enabled debug output and the message is received before the second client has joined, the reason why this doesn't seem to happen with two desktop clients is probably that they take the same amount of time to join.

In hindsight it's obvious that after `join_matched_async()` returns it's not guaranteed that everyone joined, but I didn't think of that at first.

I guess there's no problem with the API then.

**Comment by Faless** [comment] 2020-05-12 12:52
I'll close the issue then.
Keep in mind that you can probably use the `received_match_presence` event (along with the presences in the `Match` object returned by the join) to know when everybody has connected.

**Closed by Faless** 2020-05-12 12:52 UTC
