### ISSUE TITLE
write_storage_objects_async cannot work as written, unsure how to fix it

### ISSUE THREAD

**Issue by SWCCGArenaProject** [heroiclabs/nakama-godot#133] opened 2022-10-02 02:27 UTC
The godot 4 branch has the method write_storage_objects_async . This method takes two parameters, the session and an array of NakamaWriteStorageObject.

NakamaWriteStorageObject has a value property which is a string.  The Nakama server is only going to accept a value that is correct and valid json. This means that the string we set for Value must include unescaped double quote characters, anything else is invalid json.

Now the catch-22, NakamaWriteStorageObject when it is serialized puts the value as entry in a dictionary which has key names names like "title" and "version".  Since this dictionary contains string keys when it is serialized they get wrapped in double-quotes, this causes the value to have its double quotes escaped or the outer payload won't be valid json.

These conditions make it effectively impossible to store an object in the server. Take for example:

await(client.client.write_storage_objects_async(client.session, [
	NakamaWriteStorageObject.new("player", "data", 1, 1, '{"test":"yes"}', "1")]))

the json payload I'm trying to save is {"test":"yes"}. However due to serialization setup described above this will be sent to the server as:

=== Nakama : DEBUG === Sending request [ID: 7, Method: PUT, Uri: http://www.kittenpanic.io:7350/v2/storage, Headers: {"Authorization":"Bearer ...}, Body: {"objects":[{"collection":"player","key":"data","permission_read":1,"permission_write":1,"value":"{\"test\":\"yes\"}","version":"1"}]}, Timeout: 3, Retries: 3, Backoff base: 10 ms]

Notice how the final payload has the value string escaped? The server will never accept this, always throws this exception:

=== Nakama : DEBUG === Request 7 returned response code: 400, RPC code: 3, error: Value must be a JSON object.
NakamaException(StatusCode={400}, Message='{Value must be a JSON object.}', GrpcStatusCode={3})

As json with escaped double-quotes is not valid json.

Am I using this API incorrectly or is it not possible for this to work right now?  How would you fix something like this, it seems like a set of impossible requirements:

1) We must escape double quotes in the payload or the outer payload is not valid json.
2) The server will not accept escaped double-quotes in the inner payload

Can we use binary serialization instead? Does anyone have this working in godot 4?

**Comment by dsnopek** [comment] 2022-10-31 18:48
Looking at the output I get when running the test suite, I see a log message like:

```
=== Nakama : DEBUG === Sending request [ID: 17, Method: PUT, Uri: http://127.0.0.1:7350/v2/storage, Headers: { "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiODU2Nzg4OC01NzFkLTQ3MzAtYjlkOS1kNTM2NTU3YjViODYiLCJ1c24iOiIyMzAxMCIsImV4cCI6MTY2NzI0MTYyNH0.8Goy5TEDaabSyUdYXRiFU6HvKkeYwtYogZDeESNMGRc" }, Body: {"objects":[{"collection":"ACollection","key":"Question","permission_read":1,"permission_write":1,"value":"{\"question\":\"Ultimate question\"}","version":""},{"collection":"ACollection","key":"Answer","permission_read":1,"permission_write":1,"value":"{\"answer\":\"42\"}","version":""}]}, Timeout: 3, Retries: 3, Backoff base: 10 ms]
```

I can see the storage values as strings with escaped JSON in them, ex: `"{\"question\":\"Ultimate question\"}"`

This is a little different than your example, where the value appears to be unescaped JSON? I'm not sure why the string wouldn't be automatically escaped for you. I'm testing with Godot v4.0-beta3 - what version are you using?

**Comment by dsnopek** [comment] 2022-11-23 20:50
Closing since I'm unable to reproduce. If you can provide more information, then we can certainly re-open this! Thanks :-)

**Closed by dsnopek** 2022-11-23 20:50 UTC
