### ISSUE TITLE
Improve error reporting and disconnect detection

### ISSUE THREAD

**Issue by mikeful** [heroiclabs/nakama-godot#84] opened 2021-09-11 15:22 UTC
I recently ran into issue where Godot client silently disconnects without error if server sends too big message. Message data is JSON encoded deck of my card game and I'll probably add some kind of compression if I end up using decks of this size in future.

Debug level logs from server:
```
{"level":"info","ts":"2021-09-11T17:21:41.767+0300","caller":"server/runtime_lua_nakama.go:1780","msg":"Sending JSON with size of 63146 characters","mid":"...","runtime":"lua"}
{"level":"debug","ts":"2021-09-11T17:21:41.772+0300","caller":"server/session_ws.go:204","msg":"Error reading message from client","uid":"...","sid":"...","error":"websocket: close 1009 (message too big)"}
{"level":"info","ts":"2021-09-11T17:21:41.773+0300","caller":"server/session_ws.go:438","msg":"Cleaning up closed client connection","uid":"...","sid":"..."}
```

Server correctly handles websocket disconnect but looks like this error is not caught/displayed anywhere on client side.

Message max size is set here and it is used to throw `WSLAY_CODE_MESSAGE_TOO_BIG = 1009` error. https://github.com/godotengine/godot/blob/master/thirdparty/wslay/includes/wslay/wslay.h#L446

I expected to get "socket_received_error" and/or "socket_closed" events from Godot client for this. Automatic reconnect or option for ignoring this error might be nice.

**Comment by dsnopek** [comment] 2022-03-16 15:36
Thanks for the bug report!

Unfortunately, I wasn't able to reproduce it. I made a Lua module with an RPC that returned JSON that was bigger than 63146 bytes (from your error message), and called it via `NakamaSocket.rpc_async()`. In my case, the big message was delivered fine (I could print it out from the client), and the socket connection remained open. If you know a better way to trigger the unexpected disconnect, please let me know!

I tried just killing Nakama after the socket was opened, to see if that could cause the problem. However, in that case, the "closed" signal on the `NakamaSocket` was correctly emitted, which is what your code should be using to detect a disconnect.

So, I'm going to close this issue for now, but if you can provide more detailed steps to reproduce, we can re-open it :-)

**Comment by mikeful** [comment] 2022-03-16 18:21
I got this error when broadcasting messages from realtime match module `match_loop()` function and not via RPC. I'll try to construct minimal match module to reproduce the error. Probably log and broadcast messages increasing in size until failure.

Shutting down server and other disconnects I have encountered were handled as expected on Godot side.

**Comment by dsnopek** [comment] 2022-03-16 18:45
Ok, great, thanks! A minimal example would be really helpful. I'll re-open this :-)

**Comment by dsnopek** [comment] 2022-04-11 15:01
Since it's been a few weeks with no new information, I'm going to close this again. But I'll happily open it again once a minimal example is posted! Thanks :-)

**Closed by dsnopek** 2022-04-11 15:01 UTC

**Comment by TypicalFooBar** [comment] 2023-12-23 00:14
I don't have an easy way to make a small example right now but wanted to add data here.

I'm also experiencing this issue when sending data in the matchLoop function (I'm using TypeScript).

I'm making an HTTP call that returns around a 50KB binary file which then gets sent to connected clients:

```
const response: nkruntime.HttpResponse = getSimulationResults(nk, ctx.matchId, state.game.round)

if (response.code === 200) {
   // Send the simulation results to the clients
   dispatcher.broadcastMessage(OpCode.SIMULATION_RESULTS, response.body)
}
```

The error I see is:

```
2023-12-22 17:41:56 {"level":"debug","ts":"2023-12-22T23:41:56.704Z","caller":"server/session_ws.go:204","msg":"Error reading message from client","uid":"c21519db-3f66-49cb-afe9-0e2e0fff20e2","sid":"a895f435-a123-11ee-8e91-7106fdcb5b46","error":"websocket: close 1009 (message too big)"}
```

Not sure how to handle this error, but to simply avoid it altogether I am considering splitting my binary file into multiple chunks and broadcasting multiple messages to clients.

**Comment by mofirouz** [comment] 2023-12-23 00:22
Best to ask these types of questions on the forum. To help you out:

1. I think generally speaking you should refrain from sending such large payloads down the wire. You should probably batch them. 

2. However if you must, there is this config you can change on the server to allow sending/receiving large socket connections (and separate config for non-socket data):

https://heroiclabs.com/docs/nakama/getting-started/configuration/#socket.max_message_size_bytes

You probably want to change a few more of the relevant settings there as well if you are changing the above.

**Comment by TypicalFooBar** [comment] 2023-12-26 14:01
Gotcha - I'll use the forums in the future; I just happened to find this
thread while searching.

Thanks for the help! I definitely will redesign how I'm sending this data
back to the clients, rather than in one big blob.

I appreciate ya!
